"""Init migration

Revision ID: 01f32f5f2032
Revises: 04ed87c42507
Create Date: 2025-02-28 20:35:50.688994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "01f32f5f2032"
down_revision: Union[str, None] = "04ed87c42507"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("students", sa.Column("created_at", sa.VARCHAR(), nullable=False))
    op.add_column("students", sa.Column("updated_at", sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("students", "updated_at")
    op.drop_column("students", "created_at")
    # ### end Alembic commands ###
